password_strength_test:
    path: /
    defaults: { _controller: W3C\PasswordStrengthBundle\Controller\DefaultController::indexAction, _format: json, _method: POST }
    requirements:
        _schemes: https
    options:
        expose: true
